### ISSUE TITLE
get ticker

### ISSUE THREAD

**Issue by wannesdemaeght** [Satoshinaire/kucoin-api#3]
From your description:

> params {pair: string} The trading pair to retrieve price ticker for. (optional, default {})

However, the parameter appears to be mandatory.
I expected to be able to put out one API call and get all tickers in a single response, is this not how it works?

```
kc.getTicker().then((result) => {
		var array = result.data
		console.log(array)
	})
	.catch((err) => {
		console.log(err)
	})
```	
Gives me this error:

```
{ NotFoundError: {"timestamp":1515632321281,"status":404,"error":"Not Found","message":"No message available","path":"/undefined/open/tick"}
    at ClientRequest.onResponse (c:\Trader\Logic\node_modules\restify-clients\lib\HttpClient.js:217:26)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
  jse_shortmsg: '',
  jse_info: {},
  message: '{"timestamp":1515632321281,"status":404,"error":"Not Found","message
":"No message available","path":"/undefined/open/tick"}',
  body:
   { timestamp: 1515632321281,
     status: 404,
     error: 'Not Found',
     message: 'No message available',
     path: '/undefined/open/tick' } }
```

**Comment by wannesdemaeght** [comment]
nevermind, figured it out :-)

**Comment by aloysius-pgast** [comment]
Hi @wannesdemaeght : did you use {pair:''} ? Just notice I could make it work this way but I'm wondering if there's a cleaner way

**Comment by wannesdemaeght** [comment]
nope, I used another function: getTradingSymbols
That does get all tickers. 
However, it is a slow function (4 seconds), will look into your workaround too.

**Comment by wannesdemaeght** [comment]
pretty much does the same thing...
Wonder if there's a way to pass an array of the markets we actually need.
Right now it seems the only viable options are EVERYTHING, or one market per call.

**Comment by aloysius-pgast** [comment]
I get similar latency for both getTicker with empty value or with a single symbol
I noticed that website is calling /market/open/symbols for https://www.kucoin.com/#/markets. So https://api.kucoin.com/v1/market/open/symbols is probably the best way to retrieve all ticks as descrived on https://kucoinapidocs.docs.apiary.io/#reference/0/market/list-trading-symbols-tick-(open)
